---
- hosts: localhost
  roles:
    - git
    - { role: zsh, plugins: "git sublime composer symfony2 history history-substring-search"}
    - php
    - mysql
    - homebrew-cask
    - { role: vagrant, plugins: ["vagrant-hostmanager", "landrush"]}
  vars:
    applications:
      - alfred

  tasks:
    # configuration of git
    - name: global .gitignore
      template: >
        src=templates/git/gitignore.j2
        dest={{ ansible_env.HOME }}/.gitignore_global

    - name: .gitconfig
      template: >
        src=templates/git/gitconfig.j2
        dest={{ ansible_env.HOME }}/.gitconfig

    # Install application with brew cask
    - name: Install applications with cask
      homebrew_cask: name={{ item }} state=present
      with_items: applications
