---
- hosts: localhost
  roles:
    - git
    - { role: zsh, plugins: "git sublime composer symfony2 history history-substring-search"}
    - php
    - mysql
    - pow

  tasks:

    # configuration of git
    - name: global .gitignore
      template: >
        src=templates/git/gitignore.j2
        dest={{ ansible_env.HOME }}/.gitignore_global

    - name: .gitconfig
      template: >
        src=templates/git/gitconfig.j2
        dest={{ ansible_env.HOME }}/.gitconfig
