---
- hosts: localhost
  roles:
    - git
    - { role: zsh, plugins: "git sublime composer symfony2 history history-substring-search"}
    - php
    - mysql
    - pow
    - homebrew-cask
    - { role: vagrant, plugins: ["vagrant-hostmanager"]}
  vars:
    applications:
      - mou # markdown editor
      - subler # video subtitle manager

  tasks:

    # configuration of git
    - name: global .gitignore
      template: >
        src=templates/git/gitignore.j2
        dest={{ ansible_env.HOME }}/.gitignore_global

    - name: .gitconfig
      template: >
        src=templates/git/gitconfig.j2
        dest={{ ansible_env.HOME }}/.gitconfig

    # Install application with brew cask
    - name: Install applications with cask
      command: /usr/local/bin/brew cask install {{ item }} creates=/opt/homebrew-cask/Caskroom/{{ item }}
      with_items: applications
