---
- name: tap phinze/cask
  homebrew_tap: tap=phinze/cask state=present

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install
  homebrew: >
    name=brew-cask
    state=present
