---
- name: configure
  template: >
    src=powconfig.j2
    dest={{ ansible_env.HOME }}/.powconfig

- name: install
  homebrew: >
    name=pow
    state=present

- name: Create the required host directories
  command: >
    mkdir -p {{ ansible_env.HOME }}/Library/Application\ Support/Pow/Hosts
    creates={{ ansible_env.HOME }}/Library/Application\ Support/Pow/Hosts

- name: Symlink to the host directories
  command: >
    ln -s {{ ansible_env.HOME }}/Library/Application\ Support/Pow/Hosts/ {{ ansible_env.HOME }}/.pow
    creates={{ ansible_env.HOME }}/.pow

- name: Setup port 80 forwarding and launchd agents
  command: pow --install-system
  sudo: yes

- name: Setup port 80 forwarding and launchd agents
  command: pow --install-local

- name: Load launchd agents
  command: launchctl load -w /Library/LaunchDaemons/cx.pow.firewall.plist
  sudo: yes

- name: Load launchd agents
  command: 'su {{ ansible_env.USER }} -c "launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/cx.pow.powd.plist"'
  sudo: yes

- name: enable in apache
  template: >
    src=zzz_pow.conf.j2
    dest=/etc/apache2/other/zzz_pow.conf
  sudo: yes
  notify:
   - restart apache
