---
- name: configure
  template: >
    src=powconfig.j2
    dest=/Users/{{ user }}/.powconfig

- name: install
  homebrew: >
    name=pow
    state=present

- name: Create the required host directories
  command: >
    mkdir -p /Users/{{ user }}/Library/Application\ Support/Pow/Hosts
    creates=/Users/{{ user }}/Library/Application\ Support/Pow/Hosts

- name: Symlink to the host directories
  command: >
    ln -s /Users/{{ user }}/Library/Application\ Support/Pow/Hosts/ /Users/{{ user }}/.pow
    creates=/Users/{{ user }}/.pow

- name: Setup port 80 forwarding and launchd agents
  command: pow --install-system
  sudo: yes

- name: Setup port 80 forwarding and launchd agents
  command: pow --install-local

- name: Load launchd agents
  command: launchctl load -w /Library/LaunchDaemons/cx.pow.firewall.plist
  sudo: yes

- name: Load launchd agents
  command: 'su {{user }} -c "launchctl load -w /Users/{{ user }}/Library/LaunchAgents/cx.pow.powd.plist"'
  sudo: yes

- name: enable in apache
  template: >
    src=zzz_pow.conf.j2
    dest=/etc/apache2/other/zzz_pow.conf
  sudo: yes
  notify:
   - restart apache
