---
- name: clone
  git: >
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=/Users/{{ user }}/.oh-my-zsh
    update=no
  sudo: no

- name: template
  shell: >
    cp /Users/{{ user }}/.oh-my-zsh/templates/zshrc.zsh-template /Users/{{ user }}/.zshrc
    creates=/Users/{{ user }}/.zshrc
  sudo: no

- name: plugins
  lineinfile: >
    dest=/Users/{{ user }}/.zshrc
    line="plugins=({{ plugins }})"
    regexp="plugins=\(.*\)"

- name: shell
  shell: chsh -s /bin/zsh
  when: ansible_env.SHELL != "/bin/zsh"
