---
- name: install
  homebrew: >
    name=dnsmasq
    state=present

- name: copy config file
  copy: >
    src=/usr/local/opt/dnsmasq/dnsmasq.conf.example
    dest=/usr/local/etc/dnsmasq.conf

- name: copy launch file
  copy: >
    src=/usr/local/opt/dnsmasq/homebrew.mxcl.dnsmasq.plist
    dest=/Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  sudo: yes

- name: auto start registration
  command: /bin/launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  sudo: yes

- name: configure dnsmasq
  lineinfile: >
    dest=/usr/local/etc/dnsmasq.conf
    insertafter=^#address=/double-click.net/127.0.0.1
    line=address=/dev/127.0.0.1
    state=present

- name: stop dnsmasq
  command: /bin/launchctl stop homebrew.mxcl.dnsmasq
  sudo: yes

- name: start dnsmasq
  command: /bin/launchctl start homebrew.mxcl.dnsmasq
  sudo: yes

- name: create resolver directory if not exist
  file: >
    path=/etc/resolver
    state=directory
  sudo: yes

- name: resolver dev
  template: >
    src=dev.j2
    dest=/etc/resolver/dev
  sudo: yes

