---

- name: install
  homebrew: >
    name=php55
    state=present
  notify:
   - restart apache

- name: packages
  homebrew: >
    name={{ item }}
    state=present
  with_items:
    - php55-intl
    - php55-xdebug
  notify:
   - restart apache

- name: enable in apache
  lineinfile: >
    dest=/etc/apache2/other/php5.conf
    line="LoadModule php5_module    /usr/local/opt/php55/libexec/apache2/libphp5.so"
    insertbefore=BOF
  sudo: yes
  notify:
   - restart apache


#- name: configure
